export  const RELATEDSCREENITEMS = [
    { label: "AGENDA", value: "AGENDA" },
    { label: "VENUE GUIDE", value: "VENUE_GUIDE" },
    { label: "SPEAKERS", value: "SPEAKERS" },
    { label: "PARTNERS", value: "PARTNERS" },
    { label: "EXHIBITORS", value: "EXHIBITORS" },
    { label: "GALLERY", value: "GALLERY" },
    // { label: "POLLS", value: "POLLS" },
    { label: "INFORMATION CENTER", value: "INFORMATION_CENTER" },
    { label: "GENERAL", value: "GENERAL" },
    { label: "AWARDS", value: "AWARDS" },
    { label: "PRIVILEGED MEMBERS", value: "PRIVILEGED_MEMBERS" },
    { label: "MEETINGS", value: "MEETINGS" },
    // { label: "POLICY", value: "POLICY" },
  ];